### ISSUE TITLE
filesize() returns 0 if the file is created earlier in the script

### ISSUE THREAD

**Issue by StraDaMa** [Kingcom/armips#129]
I'm not sure if this is by design or not but it has been an issue. Files created earlier in the script return 0 size if checked later in the file after it is closed.
Example:
```
.nds
.create "a.bin",0
.byte 1,1,1,1
.close

.notice fileexists("a.bin")
.notice filesize("a.bin")
```
The expectation here is after the .close the file is created and the notices should be
1 and 4. Instead the notices are 0 and 0.
Simply running the script again gives the expected result.

**Comment by Kingcom** [comment]
That is by design. Data is only written to the output files at the very end, after all the input was validated and ensured to be error-free. All the computations of immediates and labels is done in earlier steps. So you cannot compute the size of a newly created file that way. You could use labels, however:
```
.create "a.bin",0
@start_of_a:
.byte 1,1,1,1
@end_of_a:
.close

.notice @end_of_a-@start_of_a
```
