### ISSUE TITLE
align requires an argument

### ISSUE THREAD

**Issue by bentley** [Kingcom/armips#50]
`Readme.md` suggests that the argument to `.align` is optional, and this seems to be the case in my old copy of armips.

```
.align [num]

Writes zeroes into the output file until the output
position is divisible by num. If num is not given,
4 will be used by default. num has to be a power of two.
```

But if I try it in git master, armips gives an error. E.g.,

```
.create "blah.bin",0
.psx
.align  
.close

$ armips foo.s
ARMIPS64 Assembler v0.8.0 (Apr 12 2016 03:22:58) by Kingcom
/tmp/foo.s(3) fatal error: Invalid alignment
/tmp/foo.s(3) error: Undefined label ".close"
Aborting.
```

If I replace the “align” with “align 4”, it works:

```
$ armips foo.s
ARMIPS64 Assembler v0.8.0 (Apr 12 2016 03:22:58) by Kingcom
Done.
```

**Comment by Kingcom** [comment]
Hm, yeah, the readme is a bit outdated. I'm currently in the process of rewriting it from scratch, but it'll still take a while.
The argument isn't optional anymore, because otherwise I can't deterministically parse the input now that the end of a line is no longer a delimiter between instructions. 

For example:
```
.align
nop
```
nop could be interpreted as either an expression consisting of a single label which holds the alignment value, or as an opcode itself.
