### ISSUE TITLE
Help me with this make error.

### ISSUE THREAD

**Issue by february-sn0w** [Kingcom/armips#52]
https://imgur.com/a/0dNPo

How can I solve this? I have no idea so need help.
My environment is windows 10 x64 msys64 with minGW64 & minGW32.

Thank you.

**Comment by Kingcom** [comment]
Hm, I never did build it with minGW. Maybe some settings are incomplete in CMakeLists? It works with Visual Studio, so that's the likeliest reason. I'm not sure which that could be unfortunately, sorry.

**Comment by queueRAM** [comment]
Not exactly the same setup, but I was able to build armips with [Msys2/mingw-w64](http://msys2.github.io/), both for 32 and 64-bit. It required some additional `CXX_FLAGS` and `LINKER_FLAGS`. Specifically, I needed to add `-municode` to the compile (to add UNICODE and _UNICODE defines) and linking (for wmain), `-lshlwapi` to linker for PathIsRelativeW(), and optionally `-static` to avoid dynamic linking with "libstdc++-6.dll". I'm no CMake expert, but I added the following to the bottom of the CMakeLists.txt to perform this for both "MinGW Makefiles" and "MSYS Makefiles" generators:
```CMake
if(MINGW)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -municode")
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
   target_link_libraries(armips shlwapi)
endif(MINGW)
```
Since I use Msys2, my cmake command looks like:
```
$ mkdir build_mingw && cd build_mingw
$ cmake -G "MSYS Makefiles" ..
$ make -j4
$ ./armips
ARMIPS64 Assembler v0.8.0 (Nov 14 2016 23:06:44) by Kingcom
Usage: armips file.asm [-temp temp.txt] [-sym symfile.sym]
```
Note: I have yet to figure out how to use toolchain files in CMake to cross-compile from mingw-w64 under Linux.
